{
 "title": "Squid Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,20s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Squid Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Squid Proxy Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Squid Proxy Version",
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheVersionId" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Squid CPU usage_percent",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheCpuUsage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Cache Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "snmpsquid",
     "query": "SELECT last(\"cacheSwapMaxSize\")*1024/last(\"cacheCurrentSwapSize\")  FROM \"snmpsquid\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cacheCurrentSwapSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1024" ], "type": "math" }
      ],
      [
       { "params": [ "cacheSwapMaxSize" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Cache Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cacheMemMaxSize\")/last(\"cacheMemUsage\")*1024  FROM \"snmpsquid\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests / HTTP Hits / HTTP Errors per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "cacheProtoClientHttpRequests",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheProtoClientHttpRequests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "cacheHTTPHits",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheHttpHits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "cacheHttpErrors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheHttpErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP InKb/OutKb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "cacheHttpInKb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheHttpInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "cacheHttpOutKb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheHttpOutKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Squid Mem Swap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheMemUsage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Squid cacheServerInKb/cacheServerOutKb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "cacheServerInKb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmpsquid",
     "query": "SELECT non_negative_difference(mean(\"cacheProtoClientHttpRequests\")) FROM \"snmpsquid\" WHERE $timeFilter GROUP BY time(1m), \"ala\" fill(null)\n",
     "select": [
      [
       { "params": [ "cacheServerInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "cacheServerOutKb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheServerOutKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Swap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheCurrentSwapSize" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Cache Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "snmpsquid",
     "select": [
      [
       { "params": [ "cacheClients" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}